// Autogenerated file. Do not edit!
#pragma once
#include <stdint.h>
#include <stdbool.h>
void pressurebc(int32_t, int32_t, int32_t, int32_t, double *, double *, int32_t, int32_t, double *, int32_t, double *, int32_t *, int32_t *, int32_t, double *, int32_t *, int32_t *, int32_t *, int32_t *, double *, double *, double);